name: Python Package using Conda

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 6 * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: root
          server: ${{secrets.IP}}
          port: 22
          ssh_private_key: ${{secrets.SSH_PRIVATE_KEY}}
          local_path: './dist/*' # 对应我们项目build的文件夹路径
          remote_path: '/home/nginx/html/website/'
